---
manufacturer: Generic
model: fiberpatch 2 * 6 par
slug: fiberpatch-2-6-par
description: 2 pcs 6 pair SC-UPC for G12 cable
default_platform: null
part_number: ''
u_height: 1.0
is_full_depth: false
subdevice_role: null
airflow: null
weight: null
weight_unit: null
comments: ''
front-ports:
- name: port1
  type: sc-upc
  color: ''
  rear_port: G12-1
  rear_port_position: 1
  label: ''
  description: ''
- name: port2
  type: sc-upc
  color: ''
  rear_port: G12-1
  rear_port_position: 2
  label: ''
  description: ''
- name: port3
  type: sc-upc
  color: ''
  rear_port: G12-1
  rear_port_position: 3
  label: ''
  description: ''
- name: port4
  type: sc-upc
  color: ''
  rear_port: G12-1
  rear_port_position: 4
  label: ''
  description: ''
- name: port5
  type: sc-upc
  color: ''
  rear_port: G12-1
  rear_port_position: 5
  label: ''
  description: ''
- name: port6
  type: sc-upc
  color: ''
  rear_port: G12-1
  rear_port_position: 6
  label: ''
  description: ''
- name: port19
  type: sc-upc
  color: ''
  rear_port: G12-2
  rear_port_position: 1
  label: ''
  description: ''
- name: port20
  type: sc-upc
  color: ''
  rear_port: G12-2
  rear_port_position: 2
  label: ''
  description: ''
- name: port21
  type: sc-upc
  color: ''
  rear_port: G12-2
  rear_port_position: 3
  label: ''
  description: ''
- name: port22
  type: sc-upc
  color: ''
  rear_port: G12-2
  rear_port_position: 4
  label: ''
  description: ''
- name: port23
  type: sc-upc
  color: ''
  rear_port: G12-2
  rear_port_position: 5
  label: ''
  description: ''
- name: port24
  type: sc-upc
  color: ''
  rear_port: G12-2
  rear_port_position: 6
  label: ''
  description: ''
rear-ports:
- name: G12-1
  type: other
  color: ''
  positions: 6
  label: ''
  description: ''
- name: G12-2
  type: other
  color: ''
  positions: 6
  label: ''
  description: ''