---
manufacturer: Generic
model: fiberpatch 24 par
slug: fiberpatch-24-par
description: 24 pair SC-UPC for G48 cable
default_platform: null
part_number: ''
u_height: 1.0
is_full_depth: false
subdevice_role: null
airflow: null
weight: null
weight_unit: null
comments: ''
front-ports:
- name: port1
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 1
  label: ''
  description: ''
- name: port2
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 2
  label: ''
  description: ''
- name: port3
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 3
  label: ''
  description: ''
- name: port4
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 4
  label: ''
  description: ''
- name: port5
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 5
  label: ''
  description: ''
- name: port6
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 6
  label: ''
  description: ''
- name: port7
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 7
  label: ''
  description: ''
- name: port8
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 8
  label: ''
  description: ''
- name: port9
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 9
  label: ''
  description: ''
- name: port10
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 10
  label: ''
  description: ''
- name: port11
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 11
  label: ''
  description: ''
- name: port12
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 12
  label: ''
  description: ''
- name: port13
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 13
  label: ''
  description: ''
- name: port14
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 14
  label: ''
  description: ''
- name: port15
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 15
  label: ''
  description: ''
- name: port16
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 16
  label: ''
  description: ''
- name: port17
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 17
  label: ''
  description: ''
- name: port18
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 18
  label: ''
  description: ''
- name: port19
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 19
  label: ''
  description: ''
- name: port20
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 20
  label: ''
  description: ''
- name: port21
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 21
  label: ''
  description: ''
- name: port22
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 22
  label: ''
  description: ''
- name: port23
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 23
  label: ''
  description: ''
- name: port24
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 24
  label: ''
  description: ''
rear-ports:
- name: G48
  type: sc
  color: ''
  positions: 24
  label: ''
  description: ''