---
manufacturer: Generic
model: fiberpatch 48 par
slug: fiberpatch-48-par
description: 96 pair SC-UPC for G96 cable
default_platform: null
part_number: ''
u_height: 1.0
is_full_depth: false
subdevice_role: null
airflow: null
weight: null
weight_unit: null
comments: ''
front-ports:
- name: port1
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 1
  label: ''
  description: ''
- name: port2
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 2
  label: ''
  description: ''
- name: port3
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 3
  label: ''
  description: ''
- name: port4
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 4
  label: ''
  description: ''
- name: port5
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 5
  label: ''
  description: ''
- name: port6
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 6
  label: ''
  description: ''
- name: port7
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 7
  label: ''
  description: ''
- name: port8
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 8
  label: ''
  description: ''
- name: port9
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 9
  label: ''
  description: ''
- name: port10
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 10
  label: ''
  description: ''
- name: port11
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 11
  label: ''
  description: ''
- name: port12
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 12
  label: ''
  description: ''
- name: port13
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 13
  label: ''
  description: ''
- name: port14
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 14
  label: ''
  description: ''
- name: port15
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 15
  label: ''
  description: ''
- name: port16
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 16
  label: ''
  description: ''
- name: port17
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 17
  label: ''
  description: ''
- name: port18
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 18
  label: ''
  description: ''
- name: port19
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 19
  label: ''
  description: ''
- name: port20
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 20
  label: ''
  description: ''
- name: port21
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 21
  label: ''
  description: ''
- name: port22
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 22
  label: ''
  description: ''
- name: port23
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 23
  label: ''
  description: ''
- name: port24
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 24
  label: ''
  description: ''
- name: port25
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 25
  label: ''
  description: ''
- name: port26
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 26
  label: ''
  description: ''
- name: port27
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 27
  label: ''
  description: ''
- name: port28
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 28
  label: ''
  description: ''
- name: port29
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 29
  label: ''
  description: ''
- name: port30
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 30
  label: ''
  description: ''
- name: port31
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 31
  label: ''
  description: ''
- name: port32
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 32
  label: ''
  description: ''
- name: port33
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 33
  label: ''
  description: ''
- name: port34
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 34
  label: ''
  description: ''
- name: port35
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 35
  label: ''
  description: ''
- name: port36
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 36
  label: ''
  description: ''
- name: port37
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 37
  label: ''
  description: ''
- name: port38
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 38
  label: ''
  description: ''
- name: port39
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 39
  label: ''
  description: ''
- name: port40
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 40
  label: ''
  description: ''
- name: port41
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 41
  label: ''
  description: ''
- name: port42
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 42
  label: ''
  description: ''
- name: port43
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 43
  label: ''
  description: ''
- name: port44
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 44
  label: ''
  description: ''
- name: port45
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 45
  label: ''
  description: ''
- name: port46
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 46
  label: ''
  description: ''
- name: port47
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 47
  label: ''
  description: ''
- name: port48
  type: sc
  color: ''
  rear_port: G48
  rear_port_position: 48
  label: ''
  description: ''

rear-ports:
- name: G96
  type: splice
  color: ''
  positions: 48
  label: ''
  description: ''