models:
  - CCS-720XP-48ZC2-2F
  - CCS-720XP-96ZC2-4F
  - CCS-720DP-24ZS-2F
  - CCS-720DP-48ZS-2F
  - DCS-7050SX3-48YC8-F
  - DCS-7280SR3K-48YC8-F
  - DCS-7050CX3-32S-F
  - DCS-7010TX-48-F
  - DCS-7050SX3-48C8-F
  - AP-C460
  - EX3300-48P
  - EX2200-48T-4G